name: Sync Branches

on:
  push:
    branches:
      - '*'

jobs:
  mirroring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: IurasogLucian/PlayDay-DEV
          ref: ${{ github.ref }}

      - name: Mirror
        uses: yesolutions/mirror-action@master
        with:
            PUSH_ALL_REFS: "true"
            REMOTE: 'ssh://git@github.com/CloudOpsWorld/PlayDev.git'
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_SSH }}
            GIT_SSH_NO_VERIFY_HOST: "true"