name: Sync Branches

on:
  push:
    branches:
      - '*'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_PRIVATE_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Install Git LFS
        run: |
            sudo apt-get update
            sudo apt-get install -y git-lfs
            git lfs install

      - name: Mirror Repository
        run: |
          git remote add mirror ssh://git@github.com/CloudOpsWorld/PlayDev.git
          git lfs fetch --all mirror
          git push --mirror mirror --force