name: Sync Branches

on:
  push:
    branches:
      - '*'

jobs:
  sync_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: IurasogLucian/PlayDay-DEV
          ref: ${{ github.ref }}

      - name: Set Up Git
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            ls -alh
            git pull -p --all
            git remote add destination https://${{secrets.GIT_TOKEN}}@github.com/CloudOpsWorld/PlayDev.git
            git push -f destination --all