name: Sync Branches

on:
  push:
    branches:
      - '*'
jobs:
    sync_branches:
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v3
            with:
                fetch-depth: 0
            - uses: yesolutions/mirror-action@master
            with:
                PUSH_ALL_REFS: "true"
                REMOTE: 'https://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@github.com/CloudOpsWorld/PlayDev'
                GIT_USERNAME: lucian-iurasog
                GIT_PASSWORD: ${{ secrets.GIT_TOKEN }}            